In [1]:
import numpy as np

### Find out the line defined by two points

In [2]:
def get_line_by_two_points(x1, x2):
    line = np.cross(x1, x2)
    print("before sqrt: ", line)
    line = line/np.sqrt(line[0]**2 + line[1]**2)
    print("for the line of equation ax + by + c = 0")
    print("a = {}, b = {}, c = {} ".format(line[0], line[1], line[2]))
    return line

In [3]:
point1 = np.asarray([1, 0, 1])
point2 = np.asarray([0, 1, 1])

In [4]:
get_line_by_two_points(point1, point2)

('before sqrt: ', array([-1, -1,  1]))
for the line of equation ax + by + c = 0
a = -0.707106781187, b = -0.707106781187, c = 0.707106781187 


array([-0.70710678, -0.70710678,  0.70710678])

### Find out the intesection of two lines and their equations

In [51]:
point1 = np.asarray([218, 16, 1])
point2 = np.asarray([42, 141, 1])
point3 = np.asarray([347, 94, 1])

In [53]:
line1 = get_line_by_two_points(point1, point2)
line2 = get_line_by_two_points(point1, point3)

for the line of equation ax + by + c = 0
a = -0.579045105368115, b = -0.815295508358306, c = 139.27656110398198 
for the line of equation ax + by + c = 0
a = -0.5174193389091943, b = 0.8557319835805907, c = 99.10570414491492 


In [67]:
ray_of_intersection = np.cross(line1, line2)

In [68]:
point_of_intersection = ray_of_intersection/ray_of_intersection[2]

In [69]:
print(point_of_intersection)

[218.  16.   1.]


#### Finding:<br>
The point of intersection will be the same as the the point which we used to find the two intersecting lines

In [72]:
np.cross([1,1,0], [-1,1,1])

array([ 1, -1,  2])

### Projective Transformation